-- =============================================================================
-- DAI-TSMS: Department of Artificial Intelligence Timetable Scheduling &
--           Management System
-- Migration: 001_initial_schema.sql
-- Run this entire file in the Supabase SQL Editor (once).
-- =============================================================================

-- Enable pgcrypto for gen_random_uuid() (already available in Supabase)
-- No explicit extension needed; gen_random_uuid() is built-in.

-- =============================================================================
-- SECTION 1: REFERENCE / SEED TABLES
-- =============================================================================

-- 2.2 academic_years
CREATE TABLE IF NOT EXISTS academic_years (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,       -- e.g. "2026"
  short_name TEXT NOT NULL UNIQUE,       -- e.g. "26"
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.3 academic_semesters
CREATE TABLE IF NOT EXISTS academic_semesters (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT NOT NULL UNIQUE,  -- SPRING | SUMMER | FALL
  short_name       TEXT NOT NULL UNIQUE,  -- SP | SU | FA
  short_code       TEXT NOT NULL UNIQUE,  -- S | SU | F
  is_system_defined BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.4 academic_periods
CREATE TABLE IF NOT EXISTS academic_periods (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                 TEXT NOT NULL UNIQUE,  -- e.g. "2026 SPRING"
  academic_year_id     UUID NOT NULL REFERENCES academic_years(id),
  academic_semester_id UUID NOT NULL REFERENCES academic_semesters(id),
  is_active            BOOLEAN NOT NULL DEFAULT false,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (academic_year_id, academic_semester_id)
);

-- 2.5 disciplines
CREATE TABLE IF NOT EXISTS disciplines (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,   -- e.g. "BS Artificial Intelligence"
  short_name TEXT NOT NULL UNIQUE,   -- e.g. "BSARIN"
  sort_order INT  NOT NULL,          -- 1=BSARIN, 2=BSADARIN, 3=MSARIN, 4=PHARIN
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.6 programs
CREATE TABLE IF NOT EXISTS programs (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,   -- Morning | Evening | Weekend
  short_name TEXT NOT NULL UNIQUE,   -- MOR | EVE | WEE
  short_code TEXT NOT NULL UNIQUE,   -- M | E | W
  sort_order INT  NOT NULL,          -- 1=M, 2=E, 3=W
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.7 semester_numbers
CREATE TABLE IF NOT EXISTS semester_numbers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,   -- 1ST | 2ND | ... | 8TH
  number     INT  NOT NULL UNIQUE,   -- 1–8
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.8 section_numbers
CREATE TABLE IF NOT EXISTS section_numbers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,   -- A | B | ... | J
  number     INT  NOT NULL UNIQUE,   -- 1–10
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.9 degree_levels
CREATE TABLE IF NOT EXISTS degree_levels (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,   -- e.g. "Bachelors of Science 16 Years"
  short_name TEXT NOT NULL UNIQUE,   -- BS | M.Sc | MS | PhD | BSAD
  number     INT  NOT NULL UNIQUE,   -- 1 | 2 | 3 | 4 | 7
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.10 campuses
CREATE TABLE IF NOT EXISTS campuses (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,   -- Bahawalpur | Rahim Yar Khan | Bahawalnagar
  short_name TEXT NOT NULL UNIQUE,   -- B | R | N
  sort_order INT  NOT NULL,          -- 1=B, 2=R, 3=N
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- SECTION 2: CORE ENTITY TABLES
-- =============================================================================

-- 2.11 sections
CREATE TABLE IF NOT EXISTS sections (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name               TEXT NOT NULL UNIQUE,  -- auto-generated by trigger
  discipline_id      UUID NOT NULL REFERENCES disciplines(id),
  semester_number_id UUID NOT NULL REFERENCES semester_numbers(id),
  section_number_id  UUID NOT NULL REFERENCES section_numbers(id),
  program_id         UUID NOT NULL REFERENCES programs(id),
  is_active          BOOLEAN NOT NULL DEFAULT true,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (discipline_id, semester_number_id, section_number_id, program_id)
);

-- 2.12 Trigger: auto-generate sections.name from component parts
CREATE OR REPLACE FUNCTION generate_section_name()
RETURNS TRIGGER AS $$
DECLARE
  disc_short TEXT;
  sem_name   TEXT;
  sec_name   TEXT;
  prog_code  TEXT;
BEGIN
  SELECT short_name INTO disc_short FROM disciplines     WHERE id = NEW.discipline_id;
  SELECT name       INTO sem_name   FROM semester_numbers WHERE id = NEW.semester_number_id;
  SELECT name       INTO sec_name   FROM section_numbers  WHERE id = NEW.section_number_id;
  SELECT short_code INTO prog_code  FROM programs          WHERE id = NEW.program_id;
  NEW.name := disc_short || '-' || sem_name || '-' || sec_name || prog_code;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_section_name ON sections;
CREATE TRIGGER trg_section_name
  BEFORE INSERT OR UPDATE ON sections
  FOR EACH ROW EXECUTE FUNCTION generate_section_name();

-- 2.13 teachers
CREATE TABLE IF NOT EXISTS teachers (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id  UUID UNIQUE REFERENCES auth.users(id),
  name          TEXT NOT NULL,
  designation   TEXT,
  expertise     TEXT,
  mobile_number TEXT,
  email         TEXT NOT NULL UNIQUE,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.14 profiles (one per auth user — stores role + first-login flag)
CREATE TABLE IF NOT EXISTS profiles (
  id                  UUID PRIMARY KEY REFERENCES auth.users(id),
  role                TEXT NOT NULL CHECK (role IN ('admin', 'teacher', 'student')),
  first_login_pending BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.15 students
CREATE TABLE IF NOT EXISTS students (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id    UUID UNIQUE REFERENCES auth.users(id),
  registration_no TEXT NOT NULL UNIQUE,
  section_id      UUID NOT NULL REFERENCES sections(id),
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.16 courses
CREATE TABLE IF NOT EXISTS courses (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                  TEXT NOT NULL,
  code                  TEXT NOT NULL UNIQUE,
  credit_hours          NUMERIC(4,1) NOT NULL,
  contact_hours_minutes INT NOT NULL CHECK (contact_hours_minutes % 15 = 0),
  is_active             BOOLEAN NOT NULL DEFAULT true,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT valid_per_slot_duration CHECK (
    (contact_hours_minutes / 2) IN (30, 45, 60, 75, 90)
  )
);

-- 2.17 rooms
CREATE TABLE IF NOT EXISTS rooms (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,
  capacity   INT  NOT NULL CHECK (capacity > 0),
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2.18 slot_durations (lookup table for valid durations)
CREATE TABLE IF NOT EXISTS slot_durations (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  minutes    INT  NOT NULL UNIQUE CHECK (minutes IN (30, 45, 60, 75, 90)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- SECTION 3: TIMETABLE TABLES
-- =============================================================================

-- 2.19 timetables
CREATE TABLE IF NOT EXISTS timetables (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name               TEXT NOT NULL,
  academic_period_id UUID NOT NULL REFERENCES academic_periods(id),
  status             TEXT NOT NULL DEFAULT 'draft'
                       CHECK (status IN ('draft', 'published', 'archived')),
  day_monday         BOOLEAN NOT NULL DEFAULT true,
  day_tuesday        BOOLEAN NOT NULL DEFAULT true,
  day_wednesday      BOOLEAN NOT NULL DEFAULT true,
  day_thursday       BOOLEAN NOT NULL DEFAULT true,
  day_friday         BOOLEAN NOT NULL DEFAULT false,
  day_saturday       BOOLEAN NOT NULL DEFAULT false,
  day_sunday         BOOLEAN NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (academic_period_id)
);

-- 2.20 course_section_assignments
CREATE TABLE IF NOT EXISTS course_section_assignments (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timetable_id UUID NOT NULL REFERENCES timetables(id) ON DELETE CASCADE,
  course_id    UUID NOT NULL REFERENCES courses(id),
  section_id   UUID NOT NULL REFERENCES sections(id),
  teacher_id   UUID NOT NULL REFERENCES teachers(id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (timetable_id, course_id, section_id)
);

-- 2.21 slots
CREATE TABLE IF NOT EXISTS slots (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timetable_id  UUID NOT NULL REFERENCES timetables(id) ON DELETE CASCADE,
  assignment_id UUID REFERENCES course_section_assignments(id),
  day_of_week   TEXT NOT NULL CHECK (
    day_of_week IN ('monday','tuesday','wednesday','thursday','friday','saturday','sunday')
  ),
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  course_id     UUID NOT NULL REFERENCES courses(id),
  teacher_id    UUID NOT NULL REFERENCES teachers(id),
  room_id       UUID NOT NULL REFERENCES rooms(id),
  section_id    UUID NOT NULL REFERENCES sections(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT valid_start_time CHECK (
    start_time >= '08:00'
    AND EXTRACT(MINUTE FROM start_time) IN (0, 15, 30, 45)
  ),
  CONSTRAINT valid_end_time CHECK (
    end_time <= '20:00'
    AND EXTRACT(MINUTE FROM end_time) IN (0, 15, 30, 45)
  ),
  CONSTRAINT start_before_end CHECK (start_time < end_time)
);

-- 2.22 swap_requests
CREATE TABLE IF NOT EXISTS swap_requests (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requesting_slot_id    UUID NOT NULL REFERENCES slots(id),
  target_slot_id        UUID NOT NULL REFERENCES slots(id),
  requesting_teacher_id UUID NOT NULL REFERENCES teachers(id),
  target_teacher_id     UUID NOT NULL REFERENCES teachers(id),
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending','approved','rejected','cancelled')),
  admin_override        BOOLEAN NOT NULL DEFAULT false,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- SECTION 4: RLS HELPER FUNCTIONS (2.23)
-- =============================================================================

-- Returns the role of the currently authenticated user
CREATE OR REPLACE FUNCTION get_user_role()
RETURNS TEXT AS $$
  SELECT role FROM profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- Returns the teachers.id for the currently authenticated teacher user
CREATE OR REPLACE FUNCTION get_teacher_id()
RETURNS UUID AS $$
  SELECT id FROM teachers WHERE auth_user_id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- Returns the section_id for the currently authenticated student user
CREATE OR REPLACE FUNCTION get_student_section_id()
RETURNS UUID AS $$
  SELECT section_id FROM students WHERE auth_user_id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- =============================================================================
-- SECTION 5: ROW LEVEL SECURITY (2.24)
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE academic_years             ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic_semesters         ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic_periods           ENABLE ROW LEVEL SECURITY;
ALTER TABLE disciplines                ENABLE ROW LEVEL SECURITY;
ALTER TABLE programs                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE semester_numbers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE section_numbers            ENABLE ROW LEVEL SECURITY;
ALTER TABLE degree_levels              ENABLE ROW LEVEL SECURITY;
ALTER TABLE campuses                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE sections                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE slot_durations             ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE students                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE timetables                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_section_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE slots                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE swap_requests              ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Reference tables: SELECT all authenticated; INSERT/UPDATE/DELETE admin only
-- Applies to: academic_years, academic_semesters, academic_periods,
--             disciplines, programs, semester_numbers, section_numbers,
--             degree_levels, campuses, sections, slot_durations
-- ---------------------------------------------------------------------------

-- academic_years
CREATE POLICY "academic_years_select_authenticated"
  ON academic_years FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "academic_years_admin_write"
  ON academic_years FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- academic_semesters
CREATE POLICY "academic_semesters_select_authenticated"
  ON academic_semesters FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "academic_semesters_admin_write"
  ON academic_semesters FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- academic_periods
CREATE POLICY "academic_periods_select_authenticated"
  ON academic_periods FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "academic_periods_admin_write"
  ON academic_periods FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- disciplines
CREATE POLICY "disciplines_select_authenticated"
  ON disciplines FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "disciplines_admin_write"
  ON disciplines FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- programs
CREATE POLICY "programs_select_authenticated"
  ON programs FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "programs_admin_write"
  ON programs FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- semester_numbers
CREATE POLICY "semester_numbers_select_authenticated"
  ON semester_numbers FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "semester_numbers_admin_write"
  ON semester_numbers FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- section_numbers
CREATE POLICY "section_numbers_select_authenticated"
  ON section_numbers FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "section_numbers_admin_write"
  ON section_numbers FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- degree_levels
CREATE POLICY "degree_levels_select_authenticated"
  ON degree_levels FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "degree_levels_admin_write"
  ON degree_levels FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- campuses
CREATE POLICY "campuses_select_authenticated"
  ON campuses FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "campuses_admin_write"
  ON campuses FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- sections
CREATE POLICY "sections_select_authenticated"
  ON sections FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "sections_admin_write"
  ON sections FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- slot_durations
CREATE POLICY "slot_durations_select_authenticated"
  ON slot_durations FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "slot_durations_admin_write"
  ON slot_durations FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- teachers: SELECT all authenticated; INSERT/UPDATE/DELETE admin only
-- ---------------------------------------------------------------------------
CREATE POLICY "teachers_select_authenticated"
  ON teachers FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "teachers_admin_write"
  ON teachers FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- profiles: SELECT own record only; UPDATE own record only
-- ---------------------------------------------------------------------------
CREATE POLICY "profiles_select_own"
  ON profiles FOR SELECT
  TO authenticated
  USING (id = auth.uid());

CREATE POLICY "profiles_update_own"
  ON profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- Admin can insert profiles (needed when creating teacher/student accounts)
CREATE POLICY "profiles_admin_insert"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- students: admin+teacher see all; student sees own; INSERT/UPDATE/DELETE admin
-- ---------------------------------------------------------------------------
CREATE POLICY "students_select_admin_teacher"
  ON students FOR SELECT
  TO authenticated
  USING (get_user_role() IN ('admin', 'teacher'));

CREATE POLICY "students_select_own"
  ON students FOR SELECT
  TO authenticated
  USING (auth_user_id = auth.uid());

CREATE POLICY "students_admin_write"
  ON students FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- courses: SELECT all authenticated; INSERT/UPDATE/DELETE admin only
-- ---------------------------------------------------------------------------
CREATE POLICY "courses_select_authenticated"
  ON courses FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "courses_admin_write"
  ON courses FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- rooms: SELECT all authenticated; INSERT/UPDATE/DELETE admin only
-- ---------------------------------------------------------------------------
CREATE POLICY "rooms_select_authenticated"
  ON rooms FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "rooms_admin_write"
  ON rooms FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- timetables: SELECT all authenticated; INSERT/UPDATE/DELETE admin only
-- ---------------------------------------------------------------------------
CREATE POLICY "timetables_select_authenticated"
  ON timetables FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "timetables_admin_write"
  ON timetables FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- course_section_assignments: SELECT all authenticated; INSERT/UPDATE/DELETE admin
-- ---------------------------------------------------------------------------
CREATE POLICY "csa_select_authenticated"
  ON course_section_assignments FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "csa_admin_write"
  ON course_section_assignments FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- slots: admin+teacher see all; student sees own section only; admin writes
-- ---------------------------------------------------------------------------
CREATE POLICY "slots_select_admin_teacher"
  ON slots FOR SELECT
  TO authenticated
  USING (get_user_role() IN ('admin', 'teacher'));

CREATE POLICY "slots_select_student_own_section"
  ON slots FOR SELECT
  TO authenticated
  USING (
    get_user_role() = 'student'
    AND section_id = get_student_section_id()
  );

CREATE POLICY "slots_admin_write"
  ON slots FOR ALL
  TO authenticated
  USING (get_user_role() = 'admin')
  WITH CHECK (get_user_role() = 'admin');

-- ---------------------------------------------------------------------------
-- swap_requests: admin sees all; teacher sees own; teacher inserts; target/admin updates
-- ---------------------------------------------------------------------------
CREATE POLICY "swap_requests_select_admin"
  ON swap_requests FOR SELECT
  TO authenticated
  USING (get_user_role() = 'admin');

CREATE POLICY "swap_requests_select_teacher_own"
  ON swap_requests FOR SELECT
  TO authenticated
  USING (
    get_user_role() = 'teacher'
    AND (
      requesting_teacher_id = get_teacher_id()
      OR target_teacher_id  = get_teacher_id()
    )
  );

CREATE POLICY "swap_requests_teacher_insert"
  ON swap_requests FOR INSERT
  TO authenticated
  WITH CHECK (
    get_user_role() = 'teacher'
    AND requesting_teacher_id = get_teacher_id()
  );

CREATE POLICY "swap_requests_update_target_teacher_or_admin"
  ON swap_requests FOR UPDATE
  TO authenticated
  USING (
    get_user_role() = 'admin'
    OR (
      get_user_role() = 'teacher'
      AND target_teacher_id = get_teacher_id()
    )
  )
  WITH CHECK (
    get_user_role() = 'admin'
    OR (
      get_user_role() = 'teacher'
      AND target_teacher_id = get_teacher_id()
    )
  );

-- =============================================================================
-- SECTION 6: approve_swap_request RPC (2.25)
-- Atomically swaps teacher_id between two slots in a single transaction.
-- =============================================================================

CREATE OR REPLACE FUNCTION approve_swap_request(swap_id UUID)
RETURNS VOID AS $$
DECLARE
  v_requesting_slot_id    UUID;
  v_target_slot_id        UUID;
  v_requesting_teacher_id UUID;
  v_target_teacher_id     UUID;
  v_status                TEXT;
BEGIN
  -- Lock and fetch the swap request
  SELECT
    requesting_slot_id,
    target_slot_id,
    requesting_teacher_id,
    target_teacher_id,
    status
  INTO
    v_requesting_slot_id,
    v_target_slot_id,
    v_requesting_teacher_id,
    v_target_teacher_id,
    v_status
  FROM swap_requests
  WHERE id = swap_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Swap request % not found', swap_id;
  END IF;

  IF v_status <> 'pending' THEN
    RAISE EXCEPTION 'Swap request % is not pending (current status: %)', swap_id, v_status;
  END IF;

  -- Swap teacher_id on the requesting slot
  UPDATE slots
  SET teacher_id = v_target_teacher_id
  WHERE id = v_requesting_slot_id;

  -- Swap teacher_id on the target slot
  UPDATE slots
  SET teacher_id = v_requesting_teacher_id
  WHERE id = v_target_slot_id;

  -- Mark the swap request as approved
  UPDATE swap_requests
  SET status = 'approved'
  WHERE id = swap_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- SECTION 7: active_period_mutex TRIGGER (2.26)
-- Ensures only one academic_periods.is_active = true at a time.
-- When a period is activated, all others are set to false.
-- =============================================================================

CREATE OR REPLACE FUNCTION enforce_active_period_mutex()
RETURNS TRIGGER AS $$
BEGIN
  -- Only act when is_active is being set to true
  IF NEW.is_active = true THEN
    UPDATE academic_periods
    SET is_active = false
    WHERE id <> NEW.id
      AND is_active = true;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS active_period_mutex ON academic_periods;
CREATE TRIGGER active_period_mutex
  BEFORE INSERT OR UPDATE OF is_active ON academic_periods
  FOR EACH ROW EXECUTE FUNCTION enforce_active_period_mutex();

-- =============================================================================
-- END OF MIGRATION
-- =============================================================================
